"""initial 12-table schema

Revision ID: 6140bcc8c836
Revises: 
Create Date: 2026-07-23 16:45:00.771257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6140bcc8c836'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psi_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('input_url', sa.String(length=2048), nullable=False),
    sa.Column('canonical_url', sa.String(length=2048), nullable=False),
    sa.Column('final_url', sa.String(length=2048), nullable=True),
    sa.Column('storage_key_url', sa.String(length=2048), nullable=False),
    sa.Column('normalized_domain', sa.String(length=255), nullable=True),
    sa.Column('strategy', sa.String(length=16), nullable=False),
    sa.Column('performance_score', sa.Integer(), nullable=True),
    sa.Column('best_practices_score', sa.Integer(), nullable=True),
    sa.Column('accessibility_score', sa.Integer(), nullable=True),
    sa.Column('seo_score', sa.Integer(), nullable=True),
    sa.Column('fcp', sa.Float(), nullable=True),
    sa.Column('lcp', sa.Float(), nullable=True),
    sa.Column('cls', sa.Float(), nullable=True),
    sa.Column('speed_index', sa.Float(), nullable=True),
    sa.Column('tti', sa.Float(), nullable=True),
    sa.Column('tbt', sa.Float(), nullable=True),
    sa.Column('runtime_error_code', sa.String(length=64), nullable=True),
    sa.Column('lighthouse_version', sa.String(length=32), nullable=True),
    sa.Column('tested_at', sa.DateTime(), nullable=False),
    sa.Column('test_date', sa.Date(), nullable=False),
    sa.Column('compat_registry_version', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('psi_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psi_result_canonical_url'), ['canonical_url'], unique=False)
        batch_op.create_index(batch_op.f('ix_psi_result_normalized_domain'), ['normalized_domain'], unique=False)
        batch_op.create_index(batch_op.f('ix_psi_result_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_psi_result_storage_key_url'), ['storage_key_url'], unique=False)

    op.create_table('scan_run',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('tables_written', sa.JSON(), nullable=False),
    sa.Column('tables_failed', sa.JSON(), nullable=False),
    sa.Column('parser_warnings', sa.JSON(), nullable=False),
    sa.Column('compat_warnings', sa.JSON(), nullable=False),
    sa.Column('compat_registry_version', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_table('psi_best_practice',
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psi_result_id', sa.Integer(), nullable=False),
    sa.Column('canonical_key', sa.String(length=64), nullable=False),
    sa.Column('source_audit_id', sa.String(length=96), nullable=False),
    sa.ForeignKeyConstraint(['psi_result_id'], ['psi_result.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('psi_best_practice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psi_best_practice_canonical_key'), ['canonical_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_psi_best_practice_psi_result_id'), ['psi_result_id'], unique=False)

    op.create_table('psi_crux_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psi_result_id', sa.Integer(), nullable=False),
    sa.Column('form_factor', sa.String(length=16), nullable=False),
    sa.Column('metric', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=24), nullable=True),
    sa.Column('p75', sa.Float(), nullable=True),
    sa.Column('good', sa.Float(), nullable=True),
    sa.Column('ni', sa.Float(), nullable=True),
    sa.Column('poor', sa.Float(), nullable=True),
    sa.Column('fid_p75', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['psi_result_id'], ['psi_result.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('psi_crux_field', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psi_crux_field_psi_result_id'), ['psi_result_id'], unique=False)

    op.create_table('psi_cwv_element',
    sa.Column('selector', sa.String(length=1024), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psi_result_id', sa.Integer(), nullable=False),
    sa.Column('canonical_key', sa.String(length=64), nullable=False),
    sa.Column('source_audit_id', sa.String(length=96), nullable=False),
    sa.ForeignKeyConstraint(['psi_result_id'], ['psi_result.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('psi_cwv_element', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psi_cwv_element_canonical_key'), ['canonical_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_psi_cwv_element_psi_result_id'), ['psi_result_id'], unique=False)

    op.create_table('psi_diagnostic',
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psi_result_id', sa.Integer(), nullable=False),
    sa.Column('canonical_key', sa.String(length=64), nullable=False),
    sa.Column('source_audit_id', sa.String(length=96), nullable=False),
    sa.ForeignKeyConstraint(['psi_result_id'], ['psi_result.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('psi_diagnostic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psi_diagnostic_canonical_key'), ['canonical_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_psi_diagnostic_psi_result_id'), ['psi_result_id'], unique=False)

    op.create_table('psi_insight',
    sa.Column('details_type', sa.String(length=16), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('savings_ms', sa.Float(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('parse_status', sa.String(length=16), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psi_result_id', sa.Integer(), nullable=False),
    sa.Column('canonical_key', sa.String(length=64), nullable=False),
    sa.Column('source_audit_id', sa.String(length=96), nullable=False),
    sa.ForeignKeyConstraint(['psi_result_id'], ['psi_result.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('psi_insight', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psi_insight_canonical_key'), ['canonical_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_psi_insight_psi_result_id'), ['psi_result_id'], unique=False)

    op.create_table('psi_main_thread',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psi_result_id', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=64), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['psi_result_id'], ['psi_result.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('psi_main_thread', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psi_main_thread_psi_result_id'), ['psi_result_id'], unique=False)

    op.create_table('psi_network_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psi_result_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('transfer_size', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['psi_result_id'], ['psi_result.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('psi_network_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psi_network_request_psi_result_id'), ['psi_result_id'], unique=False)

    op.create_table('psi_opportunity',
    sa.Column('wasted_bytes', sa.Integer(), nullable=True),
    sa.Column('wasted_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psi_result_id', sa.Integer(), nullable=False),
    sa.Column('canonical_key', sa.String(length=64), nullable=False),
    sa.Column('source_audit_id', sa.String(length=96), nullable=False),
    sa.ForeignKeyConstraint(['psi_result_id'], ['psi_result.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('psi_opportunity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psi_opportunity_canonical_key'), ['canonical_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_psi_opportunity_psi_result_id'), ['psi_result_id'], unique=False)

    op.create_table('psi_resource_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psi_result_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('transfer_size', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['psi_result_id'], ['psi_result.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('psi_resource_summary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psi_resource_summary_psi_result_id'), ['psi_result_id'], unique=False)

    op.create_table('psi_script',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psi_result_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('total_ms', sa.Float(), nullable=True),
    sa.Column('wasted_bytes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['psi_result_id'], ['psi_result.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('psi_script', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psi_script_psi_result_id'), ['psi_result_id'], unique=False)

    op.create_table('psi_third_party',
    sa.Column('entity', sa.String(length=255), nullable=True),
    sa.Column('transfer_size', sa.Integer(), nullable=True),
    sa.Column('blocking_time', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('psi_result_id', sa.Integer(), nullable=False),
    sa.Column('canonical_key', sa.String(length=64), nullable=False),
    sa.Column('source_audit_id', sa.String(length=96), nullable=False),
    sa.ForeignKeyConstraint(['psi_result_id'], ['psi_result.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('psi_third_party', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_psi_third_party_canonical_key'), ['canonical_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_psi_third_party_psi_result_id'), ['psi_result_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('psi_third_party', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psi_third_party_psi_result_id'))
        batch_op.drop_index(batch_op.f('ix_psi_third_party_canonical_key'))

    op.drop_table('psi_third_party')
    with op.batch_alter_table('psi_script', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psi_script_psi_result_id'))

    op.drop_table('psi_script')
    with op.batch_alter_table('psi_resource_summary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psi_resource_summary_psi_result_id'))

    op.drop_table('psi_resource_summary')
    with op.batch_alter_table('psi_opportunity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psi_opportunity_psi_result_id'))
        batch_op.drop_index(batch_op.f('ix_psi_opportunity_canonical_key'))

    op.drop_table('psi_opportunity')
    with op.batch_alter_table('psi_network_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psi_network_request_psi_result_id'))

    op.drop_table('psi_network_request')
    with op.batch_alter_table('psi_main_thread', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psi_main_thread_psi_result_id'))

    op.drop_table('psi_main_thread')
    with op.batch_alter_table('psi_insight', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psi_insight_psi_result_id'))
        batch_op.drop_index(batch_op.f('ix_psi_insight_canonical_key'))

    op.drop_table('psi_insight')
    with op.batch_alter_table('psi_diagnostic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psi_diagnostic_psi_result_id'))
        batch_op.drop_index(batch_op.f('ix_psi_diagnostic_canonical_key'))

    op.drop_table('psi_diagnostic')
    with op.batch_alter_table('psi_cwv_element', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psi_cwv_element_psi_result_id'))
        batch_op.drop_index(batch_op.f('ix_psi_cwv_element_canonical_key'))

    op.drop_table('psi_cwv_element')
    with op.batch_alter_table('psi_crux_field', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psi_crux_field_psi_result_id'))

    op.drop_table('psi_crux_field')
    with op.batch_alter_table('psi_best_practice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psi_best_practice_psi_result_id'))
        batch_op.drop_index(batch_op.f('ix_psi_best_practice_canonical_key'))

    op.drop_table('psi_best_practice')
    op.drop_table('scan_run')
    with op.batch_alter_table('psi_result', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_psi_result_storage_key_url'))
        batch_op.drop_index(batch_op.f('ix_psi_result_run_id'))
        batch_op.drop_index(batch_op.f('ix_psi_result_normalized_domain'))
        batch_op.drop_index(batch_op.f('ix_psi_result_canonical_url'))

    op.drop_table('psi_result')
    # ### end Alembic commands ###
